name: App CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install Dependencies and create NPM cache
        run: npm ci

      - name: Compile Typescript and Build
        run: npm run build

      - name: Archive Build
        uses: actions/upload-artifact@v3
        with:
          name: app-dist
          path: ./dist

  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download App Dist
        uses: actions/download-artifact@v3
        with:
          name: app-dist
          path: dist

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

  create-release-notes:
    name: Create Release Notes
    runs-on: ubuntu-latest
    needs: deploy
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download App Dist
        uses: actions/download-artifact@v3
        with:
          name: app-dist
          path: dist

      - name: Generate Semantic Version and Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          git-message: "chore(release): {version}"
          release-count: 0
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Create Release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "coverage.zip"
          tag: ${{ steps.changelog.outputs.tag }}
          makeLatest: true
          body: ${{ steps.changelog.outputs.clean_changelog }}
